config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :companies do 
    resources :claims, only: :create
  end

  root 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :claims, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  
  def create 
    @claim = Claim.new(
      content: params[:claim][:content],
      company: Company.find(params[:company_id])
    )
    @claim.save 
    respond_to :js
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
    @company = Company.new
    @companies = Company.all 
  end

  def show
    @company = Company.find(params[:id]) 
    @claim = Claim.new
    respond_to :js
  end

  def create
    @company = Company.new(name: params[:company][:name])
    @company.user = current_user
    @company.save 
    respond_to :js
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    respond_to :js
  end

  def edit 
    @company = Company.find(params[:id])
    respond_to :js
  end

  def update
    @company = Company.find(params[:id])
    @company.name = params[:company][:name]
    @company.save
    respond_to :js
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/claims/create.js.erb
$('#claim_lista').prepend("<li><%= @claim.content %></li>")

app/views/companies/_claims.html.erb
<%= form_with(model: [company, claim]) do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<ul id="claim_lista">
 <% company.claims.each do |claim| %>
  <%= claim.content %>
 <% end %>
</ul>

app/views/companies/_company.html.erb
<li id="<%= company.id %>">
  <%= company.name %>
  <%= link_to "Show", company_path(company.id), data: { remote: true} %> 
  <%= link_to "Edit", edit_company_path(company.id), data: { remote: true} %> 
  <%= link_to "Destroy", company_path(company.id), method: :delete, data: { remote: true} %>
</li>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/companies/create.js.erb
$('#lista').append("<%= j render @company %>")
$('#company_name').val('')

app/views/companies/destroy.js.erb
$('#<%= @company.id %>').toggle(400)

app/views/companies/edit.js.erb
$('.modal-body').html("<%= j render 'form', company: @company %>")
$('.modal').modal('show')

app/views/companies/index.html.erb
<h1>Index</h1>

<%= render 'form', company: @company  %>

<ul id='lista'>
 <%= render @companies %>
</ul>

<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/companies/show.js.erb
$('.modal-body').html("<h5>Company: <%= @company.name %></h5> <%= j render 'claims', company: @company, claim: @claim %>")
$('.modal').modal('show')

app/views/companies/update.js.erb
$('#<%= @company.id %>').replaceWith("<%= j render @company %>")
$('.modal').modal('hide')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaAjax5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice.present? %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert"><%= alert %></p>
    <% end %>

    <%= render 'shared/navbar' %>
    
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path%>">Company</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
         <%= link_to "Iniciar sesion", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Registrate", new_user_registration_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>